---
title: "Data Manipulation"
output: github_document
---

```{r setup}
library(tidyverse)
```

## Load in the FAS Litters Data

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## `select`

Choose some columns and not others

```{r}
select(litters_df, group, gd0_weight)
```

```{r}
select(litters_df, group, gd0_weight:gd_of_birth) # group + gd0_weight to gd_of_birth
```

```{r}
select(litters_df, -litter_number) # only get rid of litter_number
```

Renaming columns ...

```{r}
select(litters_df, GROUP = group, LITTer_NumBER = litter_number) #select the columns and rename
```

```{r}
rename(litters_df, GROUP = group, LITTer_NumBER = litter_number)
# if dont want to worry about selecting
# remame function keeps everything, but to rename the two mentioned
```

Select helpers

```{r}
select(litters_df, starts_with("gd")) #select any columns with "gd"
```

```{r}
select(litters_df, litter_number, everything()) #move litter_number to the beginning
#and keep everything else
```

```{r}
relocate(litters_df, litter_number)
#relocate litter_number of the beginning
```

##  `filter` is used to remove rows or keep rows

```{r}
filter(litters_df, gd0_weight < 22)
# filter and keep only weights below 22
```

```{r}
filter(litters_df, gd0_weight >= 22)
# filter and keep only weights above 22
```

```{r}
filter(litters_df, gd_of_birth == 20) # == is used to test equality, not trying to replace
```

```{r}
filter(litters_df, !(gd_of_birth == 20)) #this is used when we have complex things
# or
filter(litters_df, gd_of_birth != 20)
#this is a simplier way to do
```

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group == "Con7")
# only see group = Con7
```

```{r}
filter(litters_df, group %in% c("Con7", "Mod8"))
# see group = Con7 and Mod8
```

##    `mutate`

modify the existing variable or create some new variables

```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight)
#create a new variable wt_gain
# and the calculation is to be gd18_weight - gd0_weight
```


```{r}
mutate(
  litters_df,
  wt_gain = gd18_weight - gd0_weight, #create new variable
  group = str_to_lower(group)) #modify existing variable

#the group = is to lowercase all group variables
#new variables created is always to the end

```

##  `arrange`

```{r}
arrange(litters_df, pups_born_alive)
```

```{r}
arrange(litters_df, pups_born_alive, gd0_weight)
#arrange pup_born_alive first
#then within pups variable, arrange gd0 weight
```













